# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doze_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_00 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_00.setObjectName("btn_00")
        self.gridLayout.addWidget(self.btn_00, 0, 0, 1, 1)
        self.btn_01 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_01.setObjectName("btn_01")
        self.gridLayout.addWidget(self.btn_01, 0, 1, 1, 1)
        self.btn_02 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_02.setObjectName("btn_02")
        self.gridLayout.addWidget(self.btn_02, 0, 2, 1, 1)
        self.btn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_10.setObjectName("btn_10")
        self.gridLayout.addWidget(self.btn_10, 1, 0, 1, 1)
        self.btn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_11.setObjectName("btn_11")
        self.gridLayout.addWidget(self.btn_11, 1, 1, 1, 1)
        self.btn_12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_12.setObjectName("btn_12")
        self.gridLayout.addWidget(self.btn_12, 1, 2, 1, 1)
        self.btn_20 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_20.setObjectName("btn_20")
        self.gridLayout.addWidget(self.btn_20, 2, 0, 1, 1)
        self.btn_21 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_21.setObjectName("btn_21")
        self.gridLayout.addWidget(self.btn_21, 2, 1, 1, 1)
        self.btn_22 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_22.setObjectName("btn_22")
        self.gridLayout.addWidget(self.btn_22, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_restart = QtWidgets.QPushButton(self.centralwidget)
        self.btn_restart.setObjectName("btn_restart")
        self.horizontalLayout.addWidget(self.btn_restart)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Doz Game"))
        self.label_status.setText(_translate("MainWindow", "your turn"))
        self.btn_restart.setText(_translate("MainWindow", "restart"))
        self.btn_exit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
