# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.Doz = QtWidgets.QPushButton(Dialog)
        self.Doz.setGeometry(QtCore.QRect(230, 70, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Doz.setFont(font)
        self.Doz.setIconSize(QtCore.QSize(50, 50))
        self.Doz.setObjectName("Doz")
        self.RPS = QtWidgets.QPushButton(Dialog)
        self.RPS.setGeometry(QtCore.QRect(230, 160, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RPS.setFont(font)
        self.RPS.setObjectName("RPS")
        self.Mine = QtWidgets.QPushButton(Dialog)
        self.Mine.setGeometry(QtCore.QRect(230, 250, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Mine.setFont(font)
        self.Mine.setObjectName("Mine")
        self.Guess = QtWidgets.QPushButton(Dialog)
        self.Guess.setGeometry(QtCore.QRect(232, 340, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Guess.setFont(font)
        self.Guess.setObjectName("Guess")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Doz.setText(_translate("Dialog", "Doz Game"))
        self.RPS.setText(_translate("Dialog", "RPS Game"))
        self.Mine.setText(_translate("Dialog", "Minesweeper"))
        self.Guess.setText(_translate("Dialog", "Guess Word"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
