# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RPS_Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RPSGameWindow(object):
    def setupUi(self, RPSGameWindow):
        RPSGameWindow.setObjectName("RPSGameWindow")
        self.centralwidget = QtWidgets.QWidget(RPSGameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout_main.addWidget(self.label_welcome)
        self.horizontalLayout_playerInfo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_playerInfo.setObjectName("horizontalLayout_playerInfo")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_playerInfo.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_playerInfo.addWidget(self.lineEdit_name)
        self.label_rounds = QtWidgets.QLabel(self.centralwidget)
        self.label_rounds.setObjectName("label_rounds")
        self.horizontalLayout_playerInfo.addWidget(self.label_rounds)
        self.spinBox_rounds = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_rounds.setMinimum(1)
        self.spinBox_rounds.setMaximum(50)
        self.spinBox_rounds.setProperty("value", 3)
        self.spinBox_rounds.setObjectName("spinBox_rounds")
        self.horizontalLayout_playerInfo.addWidget(self.spinBox_rounds)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_playerInfo.addWidget(self.btn_start)
        self.verticalLayout_main.addLayout(self.horizontalLayout_playerInfo)
        self.label_instruction = QtWidgets.QLabel(self.centralwidget)
        self.label_instruction.setObjectName("label_instruction")
        self.verticalLayout_main.addWidget(self.label_instruction)
        self.layout_buttons = QtWidgets.QHBoxLayout()
        self.layout_buttons.setObjectName("layout_buttons")
        self.btn_rock = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rock.setObjectName("btn_rock")
        self.layout_buttons.addWidget(self.btn_rock)
        self.btn_paper = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paper.setObjectName("btn_paper")
        self.layout_buttons.addWidget(self.btn_paper)
        self.btn_scissors = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scissors.setObjectName("btn_scissors")
        self.layout_buttons.addWidget(self.btn_scissors)
        self.btn_water = QtWidgets.QPushButton(self.centralwidget)
        self.btn_water.setObjectName("btn_water")
        self.layout_buttons.addWidget(self.btn_water)
        self.btn_fire = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fire.setObjectName("btn_fire")
        self.layout_buttons.addWidget(self.btn_fire)
        self.btn_earth = QtWidgets.QPushButton(self.centralwidget)
        self.btn_earth.setObjectName("btn_earth")
        self.layout_buttons.addWidget(self.btn_earth)
        self.verticalLayout_main.addLayout(self.layout_buttons)
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_main.addWidget(self.label_result)
        self.layout_scores = QtWidgets.QHBoxLayout()
        self.layout_scores.setObjectName("layout_scores")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setObjectName("label_score")
        self.layout_scores.addWidget(self.label_score)
        self.btn_show_scores = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_scores.setObjectName("btn_show_scores")
        self.layout_scores.addWidget(self.btn_show_scores)
        self.verticalLayout_main.addLayout(self.layout_scores)
        RPSGameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RPSGameWindow)
        QtCore.QMetaObject.connectSlotsByName(RPSGameWindow)

    def retranslateUi(self, RPSGameWindow):
        _translate = QtCore.QCoreApplication.translate
        RPSGameWindow.setWindowTitle(_translate("RPSGameWindow", "RPS Extended Game"))
        self.label_welcome.setText(_translate("RPSGameWindow", "Welcome to Rock, Paper, Scissors, Water, Fire, Earth Game!"))
        self.label_name.setText(_translate("RPSGameWindow", "Player Name:"))
        self.label_rounds.setText(_translate("RPSGameWindow", "Rounds:"))
        self.btn_start.setText(_translate("RPSGameWindow", "Start Game"))
        self.label_instruction.setText(_translate("RPSGameWindow", "Choose your move:"))
        self.btn_rock.setText(_translate("RPSGameWindow", "Rock"))
        self.btn_paper.setText(_translate("RPSGameWindow", "Paper"))
        self.btn_scissors.setText(_translate("RPSGameWindow", "Scissors"))
        self.btn_water.setText(_translate("RPSGameWindow", "Water"))
        self.btn_fire.setText(_translate("RPSGameWindow", "Fire"))
        self.btn_earth.setText(_translate("RPSGameWindow", "Earth"))
        self.label_result.setText(_translate("RPSGameWindow", "Round result will be shown here."))
        self.label_score.setText(_translate("RPSGameWindow", "Wins: 0 | Losses: 0 | Ties: 0"))
        self.btn_show_scores.setText(_translate("RPSGameWindow", "Show Previous Scores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RPSGameWindow = QtWidgets.QMainWindow()
    ui = Ui_RPSGameWindow()
    ui.setupUi(RPSGameWindow)
    RPSGameWindow.show()
    sys.exit(app.exec_())
